# Generated by Django 5.2.12 on 2026-03-17 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_qr_code',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_unique_id',
            field=models.UUIDField(default=uuid.UUID('a0c4d1d3-8bfe-456c-b10a-6cda977c0828'), unique=True),
        ),
    ]
