# Generated by Django 5.2.12 on 2026-03-17 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0002_alter_table_table_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='table_qr_code'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_unique_id',
            field=models.UUIDField(default=uuid.UUID('18dc3298-d486-4b6c-8773-3c61ea73c950'), unique=True),
        ),
    ]
